### ISSUE TITLE
Getting an "uninitialized constant Webrat::MechanizeSession (NameError)" when I run bin/cucumber-nagios

### ISSUE THREAD

**Issue by jeremypruitt** [auxesis/cucumber-nagios#1]
I follow the instructions provided, but every time I end up with the following error:

```
"uninitialized constant Webrat::MechanizeSession (NameError)"
```

I have searched for that error and come up with nothing. I have inspected the env.rb file in my porject directory and it definitely require rubygems, webrat, and webrat/mechanize, but it's still complaining about this line:

```
class MechanizeWorld < Webrat::MechanizeSession
```

And I'm not sure why. I have tried edtiing the env.rb file to look more like the older webrat mechanize stuff like this:

```
Webrat.configure do |config|
  config.mode = :mechanize
end
```

But that didn't work either. Both my self and a co-worker have tried this on OSX 10.5, OSX 10.6, and Fedora 8 and all with the exact same results. Any help is greatly appreciated :)

**Comment by jeremypruitt** [comment]
Ok, it looks like this webrat commit:

```
http://github.com/brynary/webrat/commit/e4ea9134a72191c70d37205d8d4533cbc894154e
```

changes MechanizeSession to MechanizeAdapter and that is breaking things. After modifying features/support/env.rb it works just fine.

**Comment by auxesis** [comment]
Hi Jeremy, 
Thanks for reporting and tracking down this bug. :-) I'll update cucumber-nagios and push a new version. 

Right now things can get a bit flaky due to the hackish bundler shipped with cucumber-nagios. A `rake deps` can pull in updated versions of the dependencies that cause breakages like this all the time. 

I'm going to switch to wycats' bundler for the next major release, which will hopefully eliminate this problem.

**Comment by lopter** [comment]
Hello,

I have gem installed cucumber-nagios today by reading the cucumber-nagios homepage.

And I'm fallen into this issue today. Am I doing something wrong ?

PS : hmm http://auxesis.github.com/cucumber-nagios/ appears to be outdated about installation...

**Comment by auxesis** [comment]
Hi lopter,
Thanks for reporting this bug. The information is indeed slightly out of date, however if you follow the quickstart instructions in the [README](http://github.com/auxesis/cucumber-nagios#readme) they should get you going. 

I'll make sure I update the website sometime today. 

Thanks!
