### ISSUE TITLE
idiots guide to xml parsing

### ISSUE THREAD

**Issue by tauboy** [auxesis/cucumber-nagios#10]
hi all

not sure if this is the correct place to raise this but I'm looking for an beginners guide to parsing xml

the problem I have is I need to write a step that will take a xpath and a value and search an xml document (web page) for a string

so for example say the webpage returns this xml stub

<resource-status>
<status>OK</status>
</resource-status>

I would want to pass in resource-status/status as the xpath and a value of OK and get the step to pass

But I cant find any examples of doing a search like this using nokogiri in cucumber-nagios so any help would be really appreciated (even if you tell me to go to another forum)

cheers

Mike

**Comment by auxesis** [comment]
You can probably get away doing this with CSS selectors: 

```
doc = Nokogiri::XML(response)
doc.search("resource-status status").first.value 
```

**Comment by tauboy** [comment]
sorted it out finally

this is the method I've come up with (it can probably be refined)

Then /^the response should have a (._) node with a value of '(._)'$/ do|xmlnode, xmlvalue|

doc = Nokogiri::XML(response.body)

  node = doc.xpath(xmlnode).first(1)

  node.to_s.should =~ /#{xmlvalue}/m

end
