### ISSUE TITLE
ssh steps will pass with SocketError

### ISSUE THREAD

**Issue by bappelt** [auxesis/cucumber-nagios#13]
If you have a step like:

Then I can ssh to "example.org" with the following credentials

but example.org is unreachable, the step will pass because it is only looking for the absence of Net::SSH::AuthenticationFailed and is perfectly happy with the presence of a SocketError

**Comment by auxesis** [comment]
Thanks for reporting this. I'll try to fix and push a new release tonight.

**Comment by LuizOz** [comment]
fix waiting to be pulled

**Comment by auxesis** [comment]
Pulled the fix, pushed out a new release (0.7.6). 

I've added your name to the [AUTHORS](http://github.com/auxesis/cucumber-nagios/blob/master/AUTHORS), if you feel like adding your email that would be sweet. :-)

Thanks for your contribution and patience on getting this merged!
