### ISSUE TITLE
cucumber-nagios 0.7.2 gen feature not working

### ISSUE THREAD

**Issue by tauboy** [auxesis/cucumber-nagios#18]
hi all

Just playing around with cucmber nagios after upgrading it to 0.7.2 and I've noticed the automatic method of creating features no longer works

so following the steps in the read me file I've:-

created a project

```
cucumber-nagios-gen project test
Generating with project generator:
     [ADDED]  .gitignore
     [ADDED]  .bzrignore
     [ADDED]  bin/cucumber-nagios-gen
     [ADDED]  bin/cucumber-nagios
     [ADDED]  Gemfile
     [ADDED]  lib/generators/feature/%feature_name%.feature
     [ADDED]  README
     [ADDED]  lib/generators/feature/%feature_name%_steps.rb
     [ADDED]  features/steps
     [ADDED]  features/support
Your new cucumber-nagios project is set up
```

then I did a gem bundle

```

cd test
gem bundle

Calculating dependencies...
Updating source: http://gems.rubyforge.org
Caching: amqp-0.6.7.gem
Caching: builder-2.1.2.gem
Caching: bundler08-0.8.5.gem
Caching: cucumber-0.6.1.gem
Downloading cucumber-nagios-0.7.0.gem
Caching: diff-lcs-1.1.2.gem
Caching: eventmachine-0.12.10.gem
Downloading extlib-0.9.15.gem
Caching: highline-1.5.2.gem
Caching: json_pure-1.4.3.gem
Caching: mechanize-0.9.3.gem
Caching: net-ssh-2.0.18.gem
Downloading nokogiri-1.4.2.gem
Downloading polyglot-0.3.1.gem
Caching: rack-1.1.0.gem
Caching: rack-test-0.5.3.gem
Caching: rake-0.8.7.gem
Caching: rspec-1.3.0.gem
Caching: templater-1.0.0.gem
Downloading term-ansicolor-1.0.5.gem
Downloading treetop-1.4.5.gem
Caching: webrat-0.7.0.gem
Installing term-ansicolor (1.0.5)
Installing builder (2.1.2)
Installing json_pure (1.4.3)
Installing net-ssh (2.0.18)
Installing eventmachine (0.12.10)
Building native extensions.  This could take a while...
Installing rack (1.1.0)
Installing rack-test (0.5.3)
Installing amqp (0.6.7)
Installing polyglot (0.3.1)
Installing rake (0.8.7)
Installing bundler08 (0.8.5)
Installing diff-lcs (1.1.2)
Installing rspec (1.3.0)
**************************************************

  Thank you for installing rspec-1.3.0

  Please be sure to read History.rdoc and Upgrade.rdoc
  for useful information about this release.

**************************************************
Installing extlib (0.9.15)
Installing nokogiri (1.4.2)
Building native extensions.  This could take a while...
Installing webrat (0.7.0)
Installing mechanize (0.9.3)
Installing treetop (1.4.5)
Installing cucumber (0.6.1)

(::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::)

                     (::)   U P G R A D I N G    (::)

Thank you for installing cucumber-0.6.1.
Please be sure to read http://wiki.github.com/aslakhellesoy/cucumber/upgrading
for important information about this release. Happy cuking!

(::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::)

Installing highline (1.5.2)
Installing templater (1.0.0)
Installing cucumber-nagios (0.7.0)
```

then tried to create a feature directory

bin/cucumber-nagios-gen feature test_feature browse
Usage: cucumber-nagios-gen generator_name [options] [args]

Generate a cucumber-nagios project.

Available generators
    project                          Generate a new self-contained cucumber-nagios project.

General options:
    -p, --pretend                    Run, but do not make any changes.
    -f, --force                      Overwrite files that already exist.
    -s, --skip                       Skip files that already exist.
    -d, --delete                     Delete files that have previously been generated with this generator.
        --no-color                   Don't colorize the output
    -h, --help                       Show this message
        --debug                      Do not catch errors

```

it looks like the cucumber-nagios-gen file in <PROGECT>/bin is not correct

cheers

Mike
```

**Comment by sysadminmike** [comment]
Hiya, 

Another Mike here with the same issues - have tried on freebsd and openbsd with no joy.  Have had a good mess around trying to figure out whats broken but havent been able to figure it out.

ta

Mike.

**Comment by irabinovitch** [comment]
Lindsay confirmed on twitter that this is a known defect and a fix is pending.  http://twitter.com/auxesis/status/14900151749

**Comment by bappelt** [comment]
Any update on this?

**Comment by proffalken** [comment]
Prod - I'd also be glad if this was fixed! ;)

I tried taking the nagios-cucumber-gen from git and patching it direct into the vendor directory but I just get constant complaints about bundle not having been run...

I've even tried reverting to cucumber-nagios 0.7.1 without sucess...

**Comment by auxesis** [comment]
Hey guys thanks for your patience on this - I'm a huge douche for not fixing this sooner. 

Looking into it right now and will have a patch pushed in the next 30 minutes.

**Comment by auxesis** [comment]
Pushed a new version of cucumber-nagios (@0.7.3@) that fixes this bug.

Thanks y'all for your patience!
