### ISSUE TITLE
Define the issue with bundler ~> 0.9

### ISSUE THREAD

**Issue by josephholsten** [auxesis/cucumber-nagios#19]
I'd definitely like bundler to meet the needs of cucumber-nagios. But "Until the bundler guys sort their shit out, I refuse to release software that uses it," isn't exactly a bug I can reproduce. I can't seem to find any bug created by you in their issue tracker, but that was just a quick skim.

What's the problem you're seeing? Is it technical? Or maybe a philosophical difference with the release schedule and backward compatibility issues? Something else entirely?

**Comment by auxesis** [comment]
I had several bad run ins with Bundler in the early 0.9's, specifically when it came to coming up with a consistent workflow. I simply couldn't get bundler to function the same way reliably across a bunch of different machines.

I actually switched to bundler 0.9 briefly on this project, but had so many issues and people hounding me with bugs that I switched to bundler08 within a week. 

Around this time I also had an IRC conversation with Yehuda & Carl about some specific workflow issues I was seeing (and ways to fix them), but my concerns were summarily ignored with passive-aggressive disdain. 

I've tried more recent versions of bundler and while the workflow issues were mostly sorted out, it pains me to be forced to use RubyGems > 1.3.5, especially when a lot of cucumber-nagios's users are running older Linux distros that don't ship up-to-the-minute RubyGems packages. 

I'm quite tempted to try out Isolate, but if you have any ideas re: bundler I'd be happy to hear them!
