### ISSUE TITLE
Make steps in webrat_steps.rb consistent

### ISSUE THREAD

**Issue by maathieu** [auxesis/cucumber-nagios#21]
Hi,

There's an extra space in the file upload regexp in webrat_steps.rb :

<pre>
When /^I attach the file at "(.*)" to "(.*)" $/ do |path, field|
--------------------------------------------^
  attach_file(field, path)
end
</pre>

This may bork some test code.

Also, I think it would be nice to add an HTTP digest authentification mechanism like this:

<pre>
Given /^I am logged in as "(.*)":"(.*)"$/ do |login, password|
        basic_auth(login, password)
end 
</pre>

So that it is available in all test cases :).

Cheers,

mathieu

**Comment by maathieu** [comment]
Also, it would be nice to add quotes to the parameter of "Going to":

<pre>
When /^I go to (.*)$/ do |path|
  visit path
end
</pre>


So that it is consistent with the others.

**Comment by auxesis** [comment]
Thanks for picking this up. I'll have some time this weekend to apply these changes.

**Comment by auxesis** [comment]
Fixed and implemented in cucumber-nagos 0.8.0.
