### ISSUE TITLE
Documentation on cucumber-nagios doesn't match steps distributed with cucumber-nagios

### ISSUE THREAD

**Issue by maathieu** [auxesis/cucumber-nagios#22]
Hi,

There is a problem on the main example on http://auxesis.github.com/cucumber-nagios/ : it reads

<pre>
Feature: google.com
  It should be up
  And I should be able to search for things

  Scenario: Searching for things
    When I visit "http://www.google.com"
    And I fill in "q" with "wikipedia"
    And I press "Google Search"
    Then I should see "www.wikipedia.org"
</pre>

But it should be:

<pre>
Feature: google.com
  It should be up
  And I should be able to search for things

  Scenario: Searching for things
    When I go to http://www.google.com
    And I fill in "q" with "wikipedia"
    And I press "Google Search"
    Then I should see "www.wikipedia.org"
</pre>

At least according to webrat_steps.rb...

I believe this would be worth a change on the main page.

Cheers,

mathieu

**Comment by auxesis** [comment]
Thanks for picking up on this. I'll make the change this weekend. :-)

**Comment by auxesis** [comment]
Fixed on cucumber-nagios.org. Thanks again!
