### ISSUE TITLE
`gem bundle` does not generate cucumber-nagios.bat on Windows

### ISSUE THREAD

**Issue by maathieu** [auxesis/cucumber-nagios#23]
Hi,

Ok, last issue report for today :-). Still using Ruby 1.9.1 on Windows XP. I managed to get my first tests running this morning, cucumber-nagios is really a wonderful tool and I am looking forward to experiment a lot with it. There is one thing though. I am running windows XP (no choice here, it's my work PC).

I generated a project following those instructions:

<pre>
$ cucumber-nagios-gen project ebay.com.au
$ cd ebay.com.au
$ gem bundle
</pre>

However, after doing this and creating my first test cases, I discovered that the command line:

<pre>
$ bin/cucumber-nagios features/ebay.com.au/bidding.feature
</pre>

would not run. As a matter of fact, there was no "cucumber-nagios.bat" in the bin directory. So I wrote one myself and then it works all right. The code looks like this:

<pre>
@ECHO OFF
IF NOT "%~f0" == "~f0" GOTO :WinNT
@"ruby.exe" "C:/my_project_directory/bin/cucumber-nagios" %1 %2 %3 %4 %5 %6 %7 %8 %9
GOTO :EOF
:WinNT
@"ruby.exe" "%~dpn0" %*
</pre>

Is it possible to add the code generation for this file in the project?

Kind regards,

Mathieu

(it's the same code as for cucumber-nagios-gen.bat).

**Comment by auxesis** [comment]
Hey there. 

Thanks for reporting this bug. I honestly haven't done any testing on Windows so I really appreciate you taking the time to report bugs. 

As I don't have a Windows machine or license it makes it difficult to implement and test, however I'd be very happy to accept any patches (even if they're semi-complete), and answer any questions you may have. 

Please let me know if there's _anything_ I can do to help, and please don't hesitate to ask any questions, no matter how silly you think they may be. :-)

**Comment by auxesis** [comment]
Hi again,
After the latest batch of refactoring, I've switched cucumber-nagios away from bundler08 in favour of vanilla bundler. Can you let me know if this is still an issue with vanilla bundler?

**Comment by auxesis** [comment]
Hey there,
This has been further mitigated by not freezing in the `cucumber-nagios` script in to the generated project, and installing it as part of the gem, callable from anywhere. 

This feels like a one-two punch to the problem, so closing. :-)
