### ISSUE TITLE
Nokogiri error with 0.6.5

### ISSUE THREAD

**Issue by lopter** [auxesis/cucumber-nagios#3]
Hello,

With a project created with the latest version of cucumber-nagios (0.6.5), I get an error with nokogiri :

<pre>
ubuntu-dotcloud:0:~/institut-telecom% bin/nokogiri                                                                               
/usr/lib/ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require': no such file to load -- nokogiri/nokogiri (LoadError)
    from /usr/lib/ruby/1.8/rubygems/custom_require.rb:36:in `require'
    from /home/louis/institut-telecom/vendor/gems/gems/nokogiri-1.4.0/lib/nokogiri.rb:13
    from /usr/lib/ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /usr/lib/ruby/1.8/rubygems/custom_require.rb:36:in `require'
    from ./bin/../vendor/gems/gems/nokogiri-1.4.0/bin/nokogiri:7
    from bin/nokogiri:3:in `load'
    from bin/nokogiri:3
</pre>

It works correctly with 0.6.3. I'm not a ruby apps writer, and I wasn't able to find the issue. (I have tried to add require 'rubygems' at some places without success).

Best Regards
- Louis Opter louis.opter@dotcloud.com

**Comment by auxesis** [comment]
Hi Louis,
I'm pretty sure this is a bug with Bundler and not cucumber-nagios. I consider pretty much anything in bin/ other than `cucumber`, `cucumber-nagios`, and `cucumber-nagios-gen` to be out of cucumber-nagios's scope. 

Regardless, you have perked my interest. :-) I tried reproducing the bug but couldn't - what version of Ruby/RubyGems you're using?

**Comment by lopter** [comment]
Thanks for your help I'm using rubygems 1.3.5 on Ubuntu 8.10

<pre>
ubuntu-dotcloud:0:~% dpkg -l ruby\* | grep -v '^un'
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Cfg-files/Unpacked/Failed-cfg/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Hold/Reinst-required/X=both-problems (Status,Err: uppercase=bad)
||/ Name                                       Version                                                    Description
+++-==========================================-==========================================================-=========================================================
ii  ruby                                       4.2                                                        An interpreter of object-oriented scripting language Ruby
ii  ruby-dev                                   4.2                                                        Header files for compiling extension modules for Ruby
ii  ruby1.8                                    1.8.7.72-1ubuntu0.2                                        Interpreter of object-oriented scripting language Ruby 1.
ii  ruby1.8-dev                                1.8.7.72-1ubuntu0.2                                        Header files for compiling extension modules for the Ruby
ii  rubygems                                   1.3.5-1ubuntu2                                             package management framework for Ruby libraries/applicati
ii  rubygems1.8                                1.3.5-1ubuntu2                                             package management framework for Ruby libraries/applicati
</pre>

**Comment by auxesis** [comment]
Hey Louis,
I'm going through and fixing up the backlog of cucumber-nagios bugs - is this still a problem for you?

**Comment by lopter** [comment]
Hi,

No, we stopped to use Ubuntu 8.10 and we don't have this problem anymore.

Thanks!

**Comment by auxesis** [comment]
Awesome.
