### ISSUE TITLE
Default feature doesn't work

### ISSUE THREAD

**Issue by bitfield** [auxesis/cucumber-nagios#38]
In cucumber-nagios 0.88, when you generate a new feature with:
# cucumber-nagios-gen feature www.google.com foo

the scaffolding file features/www.google.com/foo.feature contains:

Feature: www.google.com
  It should be up

  Scenario: Visiting home page
    When I visit "http://www.google.com"
    Then the request should succeed

This actually fails under Cucumber, since the 'visit' step isn't defined. It should be 'go to' instead of 'visit'. If you make this change, the feature passes.

**Comment by auxesis** [comment]
This is a regression. I have a test for it but apparently the test is broken. 

I'll try and get this fixed today.

**Comment by auxesis** [comment]
This has been fixed in 0.8.9. 

Thanks for pointing out this bug! :-)
