### ISSUE TITLE
gem bundle not working

### ISSUE THREAD

**Issue by simonzh** [auxesis/cucumber-nagios#4]
I've seen your demo at Fosdem, couldn't wait to go home and make my monitoring more delicious now  I'm already stuck at 3rd step of your howto:

argnagios:~/ebay.com.au # gem install bundler
Due to a rubygems bug, you must uninstall all older versions of bundler for 0.9 to work
Successfully installed bundler-0.9.5
1 gem installed
Installing ri documentation for bundler-0.9.5...
Installing RDoc documentation for bundler-0.9.5...
argnagios:~/ebay.com.au # gem bundle
ERROR:  While executing gem ... (RuntimeError)
    Unknown command bundle

any help really appreciated.

**Comment by auxesis** [comment]
The latest versions of bundler are completely backwards incompatible, so you can kindly blame bundler for all your install troubles. :-)

I suggest you downgrade to bundler 0.8 and everything should work. Once the bundler guys have finished breaking stuff every release I'll upgrade cucumber-nagios + Visage to use the latest and greatest stuff. 

The magic incantations you require are:

```
gem uninstall bundler
gem install bundler -v 0.8
```

Let me know if you have any more trouble!

**Comment by simonzh** [comment]
gem bundle
Calculating dependencies...
Updating source: http://gems.rubyforge.org
Installing nokogiri (1.4.1)
Building native extensions.  This could take a while...
ERROR:  While executing gem ... (Gem::Installer::ExtensionBuildError)
    ERROR: Failed to build gem native extension.

/usr/bin/ruby extconf.rb
checking for iconv.h in /opt/local/include/,/opt/local/include/libxml2,/opt/local/include,/opt/local/include,/opt/local/include/libxml2,/usr/local/include,/usr/local/include/libxml2,/usr/include,/usr/include/libxml2,/usr/include,/usr/include/libxml2... no
iconv is missing.  try 'port install iconv' or 'yum install iconv'
**\* extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

buuuuut:

ll /usr/include/iconv.h
-rw-r--r-- 1 root root 1949 Jan 27 13:25 /usr/include/iconv.h

**Comment by simonzh** [comment]
by the way: libxml2-devel and libxslt-devel are installed - still, same problem.

trying to run this on opensuse :(

**Comment by simonzh** [comment]
any reason why I need nokogiri standalone? There's a precompiled package for suse, it installs well, I can run executable...

**Comment by auxesis** [comment]
There's nothing stopping you from using it standalone, but the purpose of the bundler is to make it easy to tar up your cuc-nag project and deploy it to a server without having to install all sorts of crazy dependencies at a system level. 

I'll have a take a closer look at this. What version of opensuse?

**Comment by auxesis** [comment]
What does `pkg-config --list-all | grep xml` give you?

**Comment by simonzh** [comment]
pkg-config --list-all | grep xml
libxml-2.0                       libXML - libXML library version2.

trying to make this run on opensuse 11.2

I'm happy to live with crazy dependencies - it just has to run on this one holy server that does all the monitoring stuff. 

Will try out writing my own .feature file and play around a bit...will keep you updated

**Comment by auxesis** [comment]
Ok great!
