### ISSUE TITLE
scripts in bin should have execute permissions

### ISSUE THREAD

**Issue by graaff** [auxesis/cucumber-nagios#5]
I've just created a new project with cucumber-nagios 0.6.7 and noticed that the scripts in the bin directory don't have execute permissions. This means that following along with the example on the homepage doesn't work since it suggests to run bin/cucumber-nagios-gen which does not work out of the box.

Easy to fix by adding the permissions, but would be nice to have that out of the box.

**Comment by auxesis** [comment]
Hmm ok this is definitely a bug. 

Can you post some steps to reproduce?

**Comment by tauboy** [comment]
just checked my newly created project and the scripts in bin are all executable, but thats on centos

**Comment by auxesis** [comment]
What platform were you originally on that trigger this bug?

**Comment by graaff** [comment]
I'm using this on Gentoo Linux, and I now see that this is an issue in our build/install stuff, so we'll need to fix it on our end. Apologies!
