### ISSUE TITLE
Switch to use Aruba (CLI), Capybara (web) and Thor (generator) gems in Generated Gemfile

### ISSUE THREAD

**Issue by hedgehog** [auxesis/cucumber-nagios#51]
**update:** Nominate Thor rather than Tilt

[Aruba](https://github.com/aslakhellesoy/aruba) for command line and some file system ops.
[Capybara](https://github.com/jnicklas/capybara) to replace Webrat for web ops.
[Thor](https://github.com/wycats/thor) to replace Templater.

The reason for these changes is to allow Cucumber-nagios to used in projects with more recent versions of Cucumber, Rspec, etc.  At the moment bundle gives quite stale gem versions, and you have to step arounf this with RVM's gemsets.

**Comment by auxesis** [comment]
All your suggestions make sense, however there are a few caveats stopping this right now: 
- Aruba is definitely the way forward for command line testing, however there's incompatibilities between it and the built in SSH steps. The SSH steps would need to be significantly reworked for Aruba to be viable. 
- Capybara is a much cleaner replacement for Webrat, however it has poor Mechanize support, which makes it pretty useless for outside-in systems + infrastructure testing. I've messed around with wrapping Mechanize with Capybara on a few other private projects, and the reliability of the results are less than satisfactory. If someone starts maintaining a solid Mechanize adapter for Capybara, then I'd be very keen to switch. 
- Tilt has much nicer templating than Templater, but it doesn't have any features analogous to Templater's actions, generators, manifolds, or command line interface. Tilt is oriented towards rendering pages for web apps, whereas Templater a replacement for [RubiGen](http://rubigen.rubyforge.org/). 

I've bumped the Gem versions in the latest release (0.9.0), which should hopefully mitigate your RVM gemset issues. Let me know if there's anything else I can do short-term to help you out.

**Comment by hedgehog** [comment]
Ack. that this is more a discussion of a way forward, in bringing a powerful default set of gems to the tester's feet.
Point taken on Tilt.  So it seems that [Thor](https://github.com/wycats/thor) is maybe the proper `modern` [generator](http://blog.plataformatec.com.br/2009/07/creating-your-own-generators-with-thor/)(just note that post is quite old...) replacement for Templater, it also allows one to replace rake and write much more flexible [tasks](http://stackoverflow.com/questions/4384346/has-anyone-figured-out-a-way-to-run-the-same-cucumber-scenario-on-multiple-browse) - see the benchmarking snippet (benchmarking in roughly 2 lines).

Example of using Thor to generate cucumber features and tasks is [here](https://github.com/kristianmandrup/cucumber-tasks)

**Comment by hedgehog** [comment]
Re: Capybara+Mechanize.

There is a [capybara-mechanize](https://github.com/jeroenvandijk/capybara-mechanize) driver.  It is active (as at Feb/2011), but may be incomplete from the perspective of Cucumber-nagios - see the todo item on the readme page.
Anyway, it appears there may be more shoulders to share any load?

Finally, thinking out loud (I've not yet dived too deep into c-n's usage), I wonder if [Akephalos](https://github.com/bernerdschaefer/akephalos) would not offer a way forward with lower effort from testers.
