### ISSUE TITLE
Abreviate project/module name/namespace

### ISSUE THREAD

**Issue by hedgehog** [auxesis/cucumber-nagios#54]
cucumber-nagios wears thin quickly, and isn't suitable namespace for re-usable modules.

Is a name change is feasible for  1.0 release?

cunag | cumnag
cuken

If not for the project/gemnames then maybe for any reusable modules namespace?

**Comment by auxesis** [comment]
Definitely not feasible. I agree that the name isn't particularly good, but the project is extremely well known by its name. 

Not keen on changing names internally either, as that just makes it way more confusing for new contributors (_"Why are the internals named differently to the project?"_)

I don't think the namespaces are _that_ cludgy. I've been maintaining cucumber-nagios for close to 2 years now, and I have little trouble doing this all over the place:

```
module Cucumber
  module Nagios
    ...
  end
end
```

For re-usable steps, maybe it would make sense to spin them out into a separate library? That way they can be required like any other RubyGem, and used across multiple projects.

**Comment by hedgehog** [comment]
I thought a reusable library should really work like Aruba, which isn't `Cucumber::Aruba`. Shouldn't we follow Cucumber's lead/experience in breaking out Aruba from Cucumber's core?  
If someone wants nagios steps they will probably want the nagios formatter, and the convenience bin.
It is definitely possible to keep `cucumber-nagios` gem and reusable step modules together, it is just that it breaks ruby's library conventions and hence POLS.

**Comment by hedgehog** [comment]
OK.  So I've got Aruba working with the current cucumber-nagios setup.

I've spun somethings out into a reusable steps namespace - cuken (pronounced: cookin')

I've modeled Cuken on Aruba and, not surprising given the experience in that project, the structure works well.  There are some steps that I'd like to push back upstream to Aruba, until then they are in Cuken.

This means that in your nagios project's feature files you can use any Aruba Steps, as well as those in the Cuken.

Documentation is an issue, i.e. summarizing the steps pre-defined.   Here I think something like Relish will come in handy.

So if I understand your comment above you'd rather see the reusable steps in a separate gem that is required by cucumber-nagios?

IF I understand correctly then cucumber nagios starts to focus more or generating more sophisticated _sets_ feature files - think best practices descriptions. 

Where as right now it seems all the effort is on generating sophisticated step definitions - which no one shares, more importantly no one can easily update - and trivial feature files.

This seems a useful way to proceed?

**Comment by hedgehog** [comment]
Auxesis asked me to take over CN, so closing this issue, since it is resolved in:
https://github.com/hedgehog/cucumber-nagios

**Comment by auxesis** [comment]
The cuken stuff looks good, awesome work!

**Comment by hedgehog** [comment]
Hmm, just waiting on chef-server 0.10.0.rc.x to be vagrant launch enabled and then I can resume some of the finishing touches.  Hopefully, cuken 0.2 will be usable. ssh-forver will probably come inside cuken as a ssh API.

So far no one has shouted the odds, but I'm included to ban password-ful ssh access steps from cuken.

**Comment by auxesis** [comment]
I think that makes a lot of sense from a best-practices perspective.
