### ISSUE TITLE
cucumber-nagios-gen should not require 'gem bundle' to be run

### ISSUE THREAD

**Issue by graaff** [auxesis/cucumber-nagios#6]
While bundling the gems might be a good approach in some cases, it won't work well for everyone so making it required is perhaps a bit too opinionated, especially when still experimenting. I've simply removed the 'exit 1' in cucumber-nagios-gen in my local copy.

**Comment by auxesis** [comment]
OK cool. Can you give me some examples where this would be useful? 

I'm on a bit of a bundler hate at the moment so very open to suggestions.

**Comment by graaff** [comment]
Personally I never bundle stuff. Instead I'd rather manage it as proper external dependencies so that bug fixes and updates also find their way to the project, rather than containing possible stale or buggy versions. So my replacement for 'gem bundle' would be... nothing :-)

I can also see the value of being able to bundle up stuff if you can't affect what is installed on a server, for example.

**Comment by jhulten** [comment]
The changes to support bundler 0.9 aren't too tricky.

```
# attempt to load up the bundled gems, and give an explanatory message if we can't
begin
  require File.join(File.dirname(__FILE__), '..', '.bundle', 'environment')
rescue LoadError
  puts "You need to bundle gems into your project before you can run this."
  puts
  puts "To do this, make sure the 'bundler' gem is installed, and run:"
  puts
  puts "  $ bundle pack"
  puts
  exit 1
end
```

I haven't done a huge amount of testing on this, but the generator runs with this change.

**Comment by auxesis** [comment]
I believe this has been fixed for a while, I just forgot to close the issue!
