### ISSUE TITLE
cant get basic tests to run

### ISSUE THREAD

**Issue by tauboy** [auxesis/cucumber-nagios#7]
hi all

just started with cucumber-nagios and have installed it on a basic centos 5.4 machine

to install I did the following

yum install ruby libxml2-devel libxslt-devel ruby-devel ruby-docs ruby-ri ruby-irb ruby-rdoc

cd /tmp
wget http://gemcutter-production.s3.amazonaws.com/rubygems/rubygems-1.3.5.tgz
tar zxfv rubygems-1.3.5.tgz
cd rubygems-1.3.5
ruby setup.rb
gem install gemcutter
gem install cucumber-nagios

gem install --version '= 0.8.0' bundler

cd ~
cucumber-nagios-gen project google
cd google/
gem bundle

bin/cucumber-nagios-gen feature google.co.uk browse
bin/cucumber-nagios features/google.co.uk/browse.feature

when I run the test it fails
Critical: 1, Warning: 0, 0 okay | passed=0, failed=1, nosteps=0, total=1

running a cucumber feature test gives me

Feature: google.co.uk
  It should be up

  Scenario: Visiting home page           # features/google.co.uk/browse.feature:4
    When I go to http://google.co.uk # features/steps/webrat_steps.rb:1
      undefined method `instance_variable_defined?' for #<Net::HTTP google.co.uk:80 open=false> (NoMethodError)
      ./features/steps/webrat_steps.rb:2:in`/^I go to (.*)$/'
      features/google.co.uk/browse.feature:5:in `When I go to http://google.co.uk'
    Then the request should succeed      # features/steps/result_steps.rb:13

Failing Scenarios:
cucumber features/google.co.uk/browse.feature:4 # Scenario: Visiting home page

1 scenario (1 failed)
2 steps (1 failed, 1 skipped)

as this is the most basic of tests I really would like to work out why it's failing can anyone help?

**Comment by tauboy** [comment]
if it helps here is a list of gems currently installed on my server

[root@localhost rubygems-1.3.5]# gem list

**\* LOCAL GEMS ***

bundler (0.9.7, 0.8.0)
cucumber-nagios (0.6.7)
diff-lcs (1.1.2)
extlib (0.9.14)
gemcutter (0.3.0)
highline (1.5.2)
json_pure (1.2.0)
rake (0.8.7)
templater (1.0.0)

```

and this is what happens when I create a project and run gem bundle

[root@localhost cucumber]# cucumber-nagios-gen project google
Generating with project generator:
     [ADDED]  README
     [ADDED]  lib/generators/feature/%feature_name%_steps.rb
     [ADDED]  features/steps/webrat_steps.rb
     [ADDED]  features/steps/result_steps.rb
     [ADDED]  features/steps/benchmark_steps.rb
     [ADDED]  features/steps/ssh_steps.rb
     [ADDED]  features/support/env.rb
     [ADDED]  features/support/nagios.rb
     [ADDED]  .gitignore
     [ADDED]  .bzrignore
     [ADDED]  Gemfile
     [ADDED]  bin/cucumber-nagios
     [ADDED]  bin/cucumber-nagios-gen
     [ADDED]  lib/generators/feature/%feature_name%.feature
Your new cucumber-nagios project is set up.

To get going, you'll need to bundle gems into the project:

  $ gem bundle

It's highly recommended you version control your projects:

  - with Git: git init ; git add . 
  - with Bazaar: bzr init ; bzr add 

[root@localhost cucumber]# cd google/
[root@localhost google]# gem bundle
Calculating dependencies...
Updating source: http://gems.rubyforge.org
Downloading builder-2.1.2.gem
Downloading cucumber-0.6.1.gem
Caching: diff-lcs-1.1.2.gem
Caching: extlib-0.9.14.gem
Caching: highline-1.5.2.gem
Caching: json_pure-1.2.0.gem
Downloading mechanize-0.9.3.gem
Downloading net-ssh-2.0.18.gem
Downloading nokogiri-1.4.1.gem
Downloading polyglot-0.3.0.gem
Downloading rack-1.1.0.gem
Downloading rspec-1.3.0.gem
Caching: templater-1.0.0.gem
Downloading term-ansicolor-1.0.4.gem
Downloading treetop-1.4.3.gem
Downloading webrat-0.6.0.gem
Installing term-ansicolor (1.0.4)
Installing builder (2.1.2)
Installing json_pure (1.2.0)
Installing net-ssh (2.0.18)
Installing rack (1.1.0)
Installing polyglot (0.3.0)
Installing diff-lcs (1.1.2)
Installing rspec (1.3.0)
**************************************************

  Thank you for installing rspec-1.3.0

  Please be sure to read History.rdoc and Upgrade.rdoc
  for useful information about this release.

**************************************************
Installing extlib (0.9.14)
Installing nokogiri (1.4.1)
Building native extensions.  This could take a while...
Installing webrat (0.6.0)
Installing mechanize (0.9.3)
Installing treetop (1.4.3)
Installing cucumber (0.6.1)

(::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::)

                     (::)   U P G R A D I N G    (::)

Thank you for installing cucumber-0.6.1.
Please be sure to read http://wiki.github.com/aslakhellesoy/cucumber/upgrading
for important information about this release. Happy cuking!

(::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::)

Installing highline (1.5.2)
Installing templater (1.0.0)
Done.
```

**Comment by auxesis** [comment]
Hey, sorry cucumber-nagios is giving you the run around. 

A few things that will help debugging: 
- What version of Ruby are you running? (cRuby, REE, JRuby)
1. run `bin/cucumber-nagios features/google.co.uk/browse.feature --debug --pretty` (note the debug + pretty flags)
2. copy the first line of output (looks something like `bin/cucumber --require ...`)
3. paste the copied line onto your command line, and add `--backtrace` to the end
4. paste the output of that command here

**Comment by tauboy** [comment]
hi mate

no need to worry about it giving me a few problems it'll help me troubleshoot issues when I start to use it in more depth

ok ruby version is
[root@localhost google]# ruby -v
ruby 1.8.5 (2006-08-25) [i386-linux]

the output of the backtrack is:-

[root@localhost google]# /opt/nagios/cucumber/google/bin/cucumber --require /opt/nagios/cucumber/google/features --format pretty features/google.co.uk/browse.feature --backtrace
Feature: google.co.uk
  It should be up

  Scenario: Visiting home page       # features/google.co.uk/browse.feature:4
    When I go to http://google.co.uk # features/steps/webrat_steps.rb:1
      undefined method `instance_variable_defined?' for #<Net::HTTP google.co.uk:80 open=false> (NoMethodError)
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/mechanize-0.9.3/lib/www/mechanize/chain/ssl_resolver.rb:20:in`handle'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/mechanize-0.9.3/lib/www/mechanize/chain.rb:30:in `pass'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/mechanize-0.9.3/lib/www/mechanize/chain/handler.rb:6:in`handle'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/mechanize-0.9.3/lib/www/mechanize/chain/connection_resolver.rb:73:in `handle'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/mechanize-0.9.3/lib/www/mechanize/chain.rb:30:in`pass'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/mechanize-0.9.3/lib/www/mechanize/chain/handler.rb:6:in `handle'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/mechanize-0.9.3/lib/www/mechanize/chain/request_resolver.rb:27:in`handle'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/mechanize-0.9.3/lib/www/mechanize/chain.rb:30:in `pass'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/mechanize-0.9.3/lib/www/mechanize/chain/handler.rb:6:in`handle'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/mechanize-0.9.3/lib/www/mechanize/chain/parameter_resolver.rb:18:in `handle'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/mechanize-0.9.3/lib/www/mechanize/chain.rb:30:in`pass'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/mechanize-0.9.3/lib/www/mechanize/chain/handler.rb:6:in `handle'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/mechanize-0.9.3/lib/www/mechanize/chain/uri_resolver.rb:72:in`handle'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/mechanize-0.9.3/lib/www/mechanize/chain.rb:25:in `handle'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/mechanize-0.9.3/lib/www/mechanize.rb:457:in`fetch_page'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/mechanize-0.9.3/lib/www/mechanize.rb:238:in `get'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/webrat-0.6.0/lib/webrat/adapters/mechanize.rb:18:in`get'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/webrat-0.6.0/lib/webrat/core/session.rb:281:in `send'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/webrat-0.6.0/lib/webrat/core/session.rb:281:in`process_request'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/webrat-0.6.0/lib/webrat/core/session.rb:122:in `request_page'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/webrat-0.6.0/lib/webrat/core/session.rb:220:in`visit'
      /opt/nagios/cucumber/google/features/steps/webrat_steps.rb:2:in `__instance_exec0'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/cucumber-0.6.1/bin/../lib/cucumber/core_ext/instance_exec.rb:26:in`send'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/cucumber-0.6.1/bin/../lib/cucumber/core_ext/instance_exec.rb:26:in `instance_exec'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/cucumber-0.6.1/bin/../lib/cucumber/core_ext/instance_exec.rb:48:in`cucumber_instance_exec'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/cucumber-0.6.1/bin/../lib/cucumber/core_ext/instance_exec.rb:69:in `cucumber_run_with_backtrace_filtering'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/cucumber-0.6.1/bin/../lib/cucumber/core_ext/instance_exec.rb:36:in`cucumber_instance_exec'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/cucumber-0.6.1/bin/../lib/cucumber/rb_support/rb_step_definition.rb:55:in `invoke'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/cucumber-0.6.1/bin/../lib/cucumber/step_match.rb:24:in`invoke'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/cucumber-0.6.1/bin/../lib/cucumber/ast/step_invocation.rb:59:in `invoke'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/cucumber-0.6.1/bin/../lib/cucumber/ast/step_invocation.rb:38:in`accept'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/cucumber-0.6.1/bin/../lib/cucumber/ast/tree_walker.rb:115:in `visit_step'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/cucumber-0.6.1/bin/../lib/cucumber/ast/tree_walker.rb:180:in`broadcast'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/cucumber-0.6.1/bin/../lib/cucumber/ast/tree_walker.rb:114:in `visit_step'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/cucumber-0.6.1/bin/../lib/cucumber/ast/step_collection.rb:15:in`accept'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/cucumber-0.6.1/bin/../lib/cucumber/ast/step_collection.rb:14:in `each'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/cucumber-0.6.1/bin/../lib/cucumber/ast/step_collection.rb:14:in`accept'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/cucumber-0.6.1/bin/../lib/cucumber/ast/tree_walker.rb:109:in `visit_steps'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/cucumber-0.6.1/bin/../lib/cucumber/ast/tree_walker.rb:180:in`broadcast'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/cucumber-0.6.1/bin/../lib/cucumber/ast/tree_walker.rb:108:in `visit_steps'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/cucumber-0.6.1/bin/../lib/cucumber/ast/scenario.rb:47:in`accept'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/cucumber-0.6.1/bin/../lib/cucumber/step_mother.rb:278:in `before_and_after'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/cucumber-0.6.1/bin/../lib/cucumber/ast/scenario.rb:45:in`accept'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/cucumber-0.6.1/bin/../lib/cucumber/ast/scenario.rb:100:in `with_visitor'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/cucumber-0.6.1/bin/../lib/cucumber/ast/scenario.rb:39:in`accept'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/cucumber-0.6.1/bin/../lib/cucumber/ast/tree_walker.rb:51:in `visit_feature_element'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/cucumber-0.6.1/bin/../lib/cucumber/ast/tree_walker.rb:180:in`broadcast'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/cucumber-0.6.1/bin/../lib/cucumber/ast/tree_walker.rb:50:in `visit_feature_element'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/cucumber-0.6.1/bin/../lib/cucumber/ast/feature.rb:26:in`accept'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/cucumber-0.6.1/bin/../lib/cucumber/ast/feature.rb:25:in `each'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/cucumber-0.6.1/bin/../lib/cucumber/ast/feature.rb:25:in`accept'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/cucumber-0.6.1/bin/../lib/cucumber/ast/tree_walker.rb:20:in `visit_feature'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/cucumber-0.6.1/bin/../lib/cucumber/ast/tree_walker.rb:180:in`broadcast'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/cucumber-0.6.1/bin/../lib/cucumber/ast/tree_walker.rb:19:in `visit_feature'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/cucumber-0.6.1/bin/../lib/cucumber/ast/features.rb:29:in`accept'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/cucumber-0.6.1/bin/../lib/cucumber/ast/features.rb:17:in `each'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/cucumber-0.6.1/bin/../lib/cucumber/ast/features.rb:17:in`each'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/cucumber-0.6.1/bin/../lib/cucumber/ast/features.rb:28:in `accept'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/cucumber-0.6.1/bin/../lib/cucumber/ast/tree_walker.rb:14:in`visit_features'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/cucumber-0.6.1/bin/../lib/cucumber/ast/tree_walker.rb:180:in `broadcast'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/cucumber-0.6.1/bin/../lib/cucumber/ast/tree_walker.rb:13:in`visit_features'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/cucumber-0.6.1/bin/../lib/cucumber/cli/main.rb:61:in `execute!'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/cucumber-0.6.1/bin/../lib/cucumber/cli/main.rb:20:in`execute'
      /opt/nagios/cucumber/google/vendor/gems/ruby/1.8/gems/cucumber-0.6.1/bin/cucumber:8
      /opt/nagios/cucumber/google/bin/cucumber:3:in `load'
      /opt/nagios/cucumber/google/bin/cucumber:3
      features/google.co.uk/browse.feature:5:in`When I go to http://google.co.uk'
    Then the request should succeed  # features/steps/result_steps.rb:13

Failing Scenarios:
cucumber features/google.co.uk/browse.feature:4 # Scenario: Visiting home page

1 scenario (1 failed)
2 steps (1 failed, 1 skipped)

hope it makes sense, as I said early I did a base install using the gem bundle to grab all the gems

cheers

Mike

**Comment by auxesis** [comment]
Hey again,
Could you download and run [this gist](https://gist.github.com/13299bb24d7c998509b6), and paste the output here? 

Thanks!

**Comment by tauboy** [comment]
hi mate

as requested

Loaded suite test
Started
.F
Finished in 0.005185 seconds.

  1) Failure:

test_inherits_from_object(NetHTTPinheritsTest) [test.rb:9]:
Exception raised:
Class: <NoMethodError>
Message: <"undefined method `instance_variable_defined?' for #<Net::HTTP google.co.uk:80 open=false>">

---Backtrace---

test.rb:11:in `test_inherits_from_object'
test.rb:9:in`test_inherits_from_object'

---

2 tests, 2 assertions, 1 failures, 0 errors

**Comment by auxesis** [comment]
That's really annoying. I did some digging, and it looks like the `instance_method_defined?` method wasn't added to Ruby until 1.8.6. 

Unfortunately CentOS/Red hat haven't packaged 1.8.6 for RHEL/Centos 5, but some kind soul has packaged it and published it in a Yum repo: 

http://krnjevic.com/wp/?p=75

Hope that helps!

**Comment by tauboy** [comment]
that did the trick

my basic test works now

thanks so much for all your help in this, but it may be worth noting the ruby version needed in the readme to save someone else having this error

cheers

Mike

**Comment by auxesis** [comment]
Yeah, I've added a personal TODO to update the documentation. 

Thanks for your help debugging the issue!
