### ISSUE TITLE
(Return code of 4 is out of bounds)  error when command ran from Nagios

### ISSUE THREAD

**Issue by strtwtsn** [auxesis/cucumber-nagios#78]
Hi, I have a command cucumber-nagios command that works fine when called from the command prompt, but when the same command get's called from inside the nagios config I get (Return code of 4 is out of bounds).

The nagios log file says

[1317643957] Warning: Return code of 4 for check of service 'Check Website is up' on host 'www.protectedplanet.net' was out of bounds.

How can I resolve this?

**Comment by hedgehog** [comment]
This seems to be a nagios issue.  Please reopen the issue if disagree and can point to a ruby stack trace showing that this gem has done something wrong.
