### ISSUE TITLE
invalid nagios output

### ISSUE THREAD

**Issue by tauboy** [auxesis/cucumber-nagios#9]
Hi mate

I just relaised the output string you are sending is invalid for nagios 3.02

plugins should return an output as described here

http://nagios.sourceforge.net/docs/3_0/pluginapi.html

e.g.

OK Critical: 0, Warning: 0, 6 okay
or
WARNING Critical: 0, Warning: 1, 5 okay

also perfdata needs to be seperated with a semi colon not a comma as yours does currently

so I guess the output should be something like

OK Critical: 0, Warning: 0, 6 okay | passed=6; failed=0; nosteps=0; total=6

it's only a minor thing but I know the guys in Nagios land are very strict on plugin output

**Comment by auxesis** [comment]
Hey there,
I believe I've fixed this is the latest version of cucumber-nagios. 

Closing, but please let me know if it's not up to scratch!
